dir_input: samples/
dir_output: samples/
input:
  # Distortion will be applied to these files (except info).
  # Set their name to null to disable distorting those images
  rgb: .rgb.png
  segments: .segments.png  # Mask of all objects in scene. 8 or 16 bit PNG.
  info: .json  # Contains camera intrinsics

workers: 0  # How many workers to use to convert files. 0 for all cores.

crop_and_resize_output: True  # Disable to get original distorted image

distortion_parameters:
  # Ref: https://docs.opencv.org/4.4.0/db/d58/group__calib3d__fisheye.html
  # These are the distortion parameters of the fisheye camera model as defined in the fisheye module of OpenCV 4.4.0
  k1: 0.17149
  k2: -0.27191
  k3: 0.25787
  k4: -0.08054

hydra:
    output_subdir: null  # Disable saving of config files. We'll do that ourselves.
    run:
        dir: .  # Set working dir to current directory
